### ISSUE TITLE
"rehype is not an XML parser"

### ISSUE THREAD

**Issue by milahu** [rehypejs/rehype#109]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

readme says "rehype is not an XML parser"
but does not help me to find an XML parser for unified

https://github.com/rehypejs/rehype/blob/620bb9cdf53a4dbe70adfca8d66c8824eb3f513f/packages/rehype-parse/readme.md?plain=1#L137-L140

### Solution

suggest an XML parser for unified

something based on [xast-util-from-xml](https://github.com/syntax-tree/xast-util-from-xml)

### Alternatives

`rehype-parse` works for simple XML files

but it fails to parse `<![CDATA[ ... ]]>`

example: [nixpkgs/doc/functions/library/attrsets.xml](https://github.com/NixOS/nixpkgs/blob/10586701d93c9654826e04f43360f8b6e219df35/doc/functions/library/attrsets.xml#L52) (docbook xml format) (https://github.com/NixOS/nixpkgs/issues/105243)

```xml
  <example xml:id="function-library-lib.attrset.attrByPath-example-value-exists">
   <title>Extracting a value from a nested attribute set</title>
<programlisting><![CDATA[
let set = { a = { b = 3; }; };
in lib.attrsets.attrByPath [ "a" "b" ] 0 set
=> 3
]]></programlisting>
  </example>
```

#### Workaround

```js
const inputText = (
  readFileSync(inputPath, 'utf8')
  // workaround for parsing xml
  // https://github.com/rehypejs/rehype/issues/109
  //.replace(/<!\[CDATA\[(.*?)\]\]>/sg, '$1')
  .replace(/<!\[CDATA\[(.*?)\]\]>/sg, '<cdata>$1</cdata>')
);
```

**Comment by wooorm** [comment]
It doesn’t exist yet, that’s why there’s no project linked.

I don‘t understand what you mean that rehype does not support CDATA. It does. HTML parsers (e.g., browsers) do support them and the HTML spec describes how to handle them. rehype follows that.

**Comment by wooorm** [comment]
Closing this one too, rehype is not an XML parser. This project can’t do what you want it too. See https://github.com/rehypejs/rehype/pull/112#issuecomment-1281298764 for more info!
