### ISSUE TITLE
rehype-parse: parse error in xml cdata with raw closing angle bracket

### ISSUE THREAD

**Issue by milahu** [rehypejs/rehype#111]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-parse@8.0.4

### Steps to reproduce

```sh
git clone https://github.com/milahu/docbook2md
cd docbook2md
git checkout  077fbf159f16e8781336a955ef0269ac9499c39e
./run.sh
```

main script: [src/docbook2md.ts](https://github.com/milahu/docbook2md/blob/077fbf159f16e8781336a955ef0269ac9499c39e/src/docbook2md.ts)

input file: [examples/attrsets.xml](https://github.com/milahu/docbook2md/blob/077fbf159f16e8781336a955ef0269ac9499c39e/examples/attrsets.xml)

relevant section:

```xml
<programlisting><![CDATA[
let set = { a = { b = 3; }; };
in lib.attrsets.attrByPath [ "a" "b" ] 0 set
=> 3
]]></programlisting>
```

### Expected behavior

correctly parse xml cdata

```js
{
  programlisting: {
    type: "element",
    tagName: "programlisting",
    children: [
      { type: "text", value: '\nlet set = { a = { b = 3; }; };\nin lib.attrsets.attrByPath [ "a" "b" ] 0 set\n=> 3' }
    ]
}
```

### Actual behavior

the parser confuses the `>` in cdata with the end of cdata

```js
{
  programlisting: {
    type: "element",
    tagName: "programlisting",
    children: [
      {
        type: "comment",
        value: '[CDATA[\nlet set = { a = { b = 3; }; };\nin lib.attrsets.attrByPath [ "a" "b" ] 0 set\n=',
        position: [Object]
      },
      { type: "text", value: "3 ]]>" }
    ]
  }
}
```

### Runtime

Deno

**Comment by wooorm** [comment]
I explained this [here](https://github.com/rehypejs/rehype/issues/109#issuecomment-1280630895): This behavior is according to the spec

```js
document.body.innerHTML = `<x><![CDATA[y]]></x>`

console.log(document.body.innerHTML)
```

->

```html
<x><!--[CDATA[y]]--></x>
```

**Comment by milahu** [comment]
> I explained this [here](https://github.com/rehypejs/rehype/issues/109#issuecomment-1280630895)

> I don‘t understand what you mean that rehype does not support CDATA. It does. HTML parsers (e.g., browsers) do support them and the HTML spec describes how to handle them. rehype follows that.

then it would ignore the `>` inside of `<![CDATA[ ... ]]>`

see also https://stackoverflow.com/questions/7092236/what-is-cdata-in-html

> Everything inside a CDATA section is ignored by the parser.
>
> A CDATA section starts with `<![CDATA[` and ends with `]]>`

**Comment by wooorm** [comment]
Your stackoverflow link is different.
- It’s about XML
- It’s about CDATA inside `script`, `style`, which are different from CDATA outside

> then it would ignore the `>` inside of `<![CDATA[ ... ]]>`

This is about the HTML5 spec. Which has been around for 10 years. It’s in every browser. We follow that so are not going to deviate. And I don’t think anyone at whatwg is interested in changing this.
See https://html.spec.whatwg.org/multipage/parsing.html#tag-open-state, which is the state for the `<` character. You can follow it, with your characters, to see what HTML defines.

---

Don’t use rehype for XML. There is no similar unified plugin system for XML, but you can use `xast` fine.
