### ISSUE TITLE
rehype-parse throws an error "cannot read property of undefined(reading spaceSeparated)" when html contain unencoded markup characters in <pre><code>.

### ISSUE THREAD

**Issue by chaoyang805** [rehypejs/rehype#127]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehyep@12.0.1

### Link to runnable example

https://code.juejin.cn/pen/7200643610050560037

### Steps to reproduce

please use this project https://code.juejin.cn/pen/7200643610050560037 to reproduce.

### Expected behavior

rehype succeed parsing the html content with some incorrect closing tags just like most browser do.

### Actual behavior

It throws an error `Cannot read properties of undefined (reading 'spaceSeparated')`

### Runtime

Node v14

### Package manager

npm 6

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks. I solved the error.
You still have to encode HTML inside HTML though, without it, you’re passing `<pre><code><x></code></pre>`, and those are actually real elements.

**Comment by chaoyang805** [comment]
> Thanks. I solved the error upstream! You still have to encode HTML inside HTML though, without it, you’re passing `\<pre\><code><x></code>\</pre\>`, and those are actually real elements.

Yes, these unencoded HTML are legacy contents and we cannot modify them. New contents will be encoded HTML.
