### ISSUE TITLE
rehype-stringify 10.0.0 does not compile

### ISSUE THREAD

**Issue by frankplow** [rehypejs/rehype#149]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-stringify v10.0.0

### Link to runnable example

_No response_ (FYI stackblitz would not run your MWE template for me)

### Steps to reproduce

Using the following snippet
```
import {unified} from 'unified'
import rehypeParse from 'rehype-parse'
import rehypeStringify from 'rehype-stringify'

const content = await unified()
    .use(rehypeParse)
    .use(rehypeStringify)
    .process('<h1>Hello World</h1>');
```

### Expected behavior

The code should run and compile the HTML to a string.

### Actual behavior

The code has the following runtime error:
```Error [TypeError]: Cannot 'process' without 'Compiler'```
and does not compile anything.

Downgrading the package to 9.0.4 fixes the issue.

### Runtime
Node.js v20.5.1

### Package manager
NPM 9.8.1

### OS

Linux

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @frankplow! 👋 
Sorry you ran into a spot of trouble.
What version of unified are you using?
Have you checked that you are running the latest version?

**Comment by frankplow** [comment]
> Welcome @frankplow! 👋 Sorry you ran into a spot of trouble. What version of unified are you using? Have you checked that you are running the latest version?

Thanks, updating to the latest unified fixed the problem. I'm afraid I did not check my package-lock.json before updating so am unable to tell you which version of unified showed the problem.

**Comment by ChristianMurphy** [comment]
Glad it's sorted!
