### ISSUE TITLE
rehype parse generates an additional <p></p> for html content

### ISSUE THREAD

**Issue by fourdim** [rehypejs/rehype#160]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-parse@9.0.0

### Link to runnable example

https://stackblitz.com/edit/github-frqzag?file=src%2Findex.ts

### Steps to reproduce

Paste following html to rehype parse:
```html
<div class="page-body">
  <p id="13d0fd81-b7f7-47ca-ae21-5b96a36c5f23" class="">aaa
  <div class="indented">
    <p id="22a66b31-b267-4924-b0c6-cf08772184b6" class="">bbb
    <div class="indented">
      <p id="d07a767a-8b5b-4d07-bb20-7657e23bf3a0" class="">ccc</p>
    </div>
    </p>
    <p id="97cd6489-e270-41bb-833c-6b55cb4b2bf4" class="">ddd</p>
  </div>
  </p>
  <p id="ee10b0a1-ee8b-4f8a-9e1d-2b1c5f09006f" class="">eee</p>
</div>
```

### Expected behavior

```html
<div class="page-body">
  <p id="13d0fd81-b7f7-47ca-ae21-5b96a36c5f23" class="">aaa
  <div class="indented">
    <p id="22a66b31-b267-4924-b0c6-cf08772184b6" class="">bbb
    <div class="indented">
      <p id="d07a767a-8b5b-4d07-bb20-7657e23bf3a0" class="">ccc</p>
    </div>
    </p>
    <p id="97cd6489-e270-41bb-833c-6b55cb4b2bf4" class="">ddd</p>
  </div>
  </p>
  <p id="ee10b0a1-ee8b-4f8a-9e1d-2b1c5f09006f" class="">eee</p>
</div>
```

### Actual behavior

```diff
<p id="13d0fd81-b7f7-47ca-ae21-5b96a36c5f23" class="">aaa
  </p><div class="indented">
    <p id="22a66b31-b267-4924-b0c6-cf08772184b6" class="">bbb
    </p><div class="indented">
      <p id="d07a767a-8b5b-4d07-bb20-7657e23bf3a0" class="">ccc</p>
    </div>
+   <p></p>
    <p id="97cd6489-e270-41bb-833c-6b55cb4b2bf4" class="">ddd</p>
  </div>
+  <p></p>
  <p id="ee10b0a1-ee8b-4f8a-9e1d-2b1c5f09006f" class="">eee</p>
```

### Runtime

Node v16

### Package manager

pnpm

### OS

Linux

### Build and bundle tools

Vite

**Comment by fourdim** [comment]
https://www.w3.org/TR/html401/struct/text.html#h-9.3.1

**Comment by wooorm** [comment]
Right, that’s how HTML works.
