### ISSUE TITLE
Include LICENSE file in the installed node_modules

### ISSUE THREAD

**Issue by MarkAshraf96** [rehypejs/rehype#179]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Including the license file in the installed node_modules, makes the packages compatible with license checkers and attribution file generators, that a lot of developers need for generating copyrights/attribution files.

### Solution

Copy the license file into all packages.

### Alternatives

Nothing on my mind.

**Comment by wooorm** [comment]
Will you do a PR for this too? Much appreciated!

**Comment by MarkAshraf96** [comment]
Yes, done  😄
