### ISSUE TITLE
Documentation: Wrong link

### ISSUE THREAD

**Issue by nbnotabene** [rehypejs/rehype#18]
### Documentation: Wrong link
In the Introduction: [https://github.com/rehypejs/rehype](https://github.com/rehypejs/rehype)

**Browse [awesome rehype]() to find out more about the ecosystem**

### Expected behaviour
Should point to https://github.com/rehypejs/awesome

### Actual behaviour
Points to https://github.com/retextjs/awesome

----
Thank You!

**Comment by wooorm** [comment]
Hey good find @nbnotabene, thanks!

Would you be up fo creating a PR with a fix?

**Comment by nbnotabene** [comment]
Sure - I will make a PR with a fix (- but beware I am not very experienced)


M.v.h.

Niels Bjerre
Lille Plads 4
DK 3740 Svaneke

mail:niels@bjerre.net
Tlf.: +45 5644 3030
Mobil: +45 2324 5554

**Comment by wooorm** [comment]
No problem, take your time, and feel free to ask questions.
