### ISSUE TITLE
Types not resolving in Deno

### ISSUE THREAD

**Issue by m-dressler** [rehypejs/rehype#187]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=issues) and [discussions](https://github.com/orgs/rehypejs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

npm:rehype@13.0.2

### Steps to reproduce

When adding rehype via `deno add npm:rehype` and then writing

```ts
import { rehype } from "rehype";

const processor = await rehype();
```

Now `processor` has type `any`. Resolving further, if inspecting the source for `rehype()` and inspecting the types for 

```ts
import type {Root} from 'hast'
import type {Processor} from 'unified'
```

The import types show "Resolved Dependency. Types: [errored]" (VS Code w/ Deno Extension)

### Actual behavior

The `Processor<...>` type isn't resolved and defaults to `any`.

### Expected behavior

The `Processor<...>` type should be resolved.

### Other attempts

Also tried installing `deno add npm:unified` & `deno add npm:hast` to see if types resolve to no avail.

### Runtime

Deno  v2.0.6

### Package manager

"

### Operating system

macOS 15.0.1 (24A348)

P.S. rehype on JSR would be amazing!

**Comment by wooorm** [comment]
> The import types show "Resolved Dependency. Types: [errored]" (VS Code w/ Deno Extension)

Did you raise it there? Why do you think the solution would be here?

**Comment by m-dressler** [comment]
@wooorm  Sorry for the late reply - you were right, it was an issue with VS Code. Sorry about the false positive. RR: JSR, I see that point. Personally using it in all my project moving forward, but simply my personal preference. Would love to see it published there, too, though. But if this is something that could be planned, I guess it'd make more sense to move it to a separate ticket.
