### ISSUE TITLE
Introduce type definitions for rehype

### ISSUE THREAD

**Issue by Rokt33r** [rehypejs/rehype#27]
## To do list

Please check items when they are resolved.

- [x] @types/hast https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41542
- [x] stringify-entities https://github.com/wooorm/stringify-entities/pull/7
- [x] parse-entities https://github.com/wooorm/parse-entities/pull/17
- [x] hast-util-to-html https://github.com/syntax-tree/hast-util-to-html/pull/17
- [x] rehype-parse
- [x] rehype-stringify
- [x] rehype
- [x] mdast-util-to-hast
- [x] remark-rehype
- [ ] rehype-raw
- [x] hast-util-sanitize
- [ ] rehype-sanitize
- [ ] hast-util-to-text
- [ ] ...TBD

**Comment by ChristianMurphy** [comment]
Awesome! Thanks @Rokt33r!
Feel free to reach out if you have questions or need a review to help with getting `@types/hast` merged into DT.

**Comment by hikerpig** [comment]
There is a [@types/hast-format](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hast-format/index.d.ts) in DT, maybe it would help?

**Comment by Rokt33r** [comment]
@hikerpig Thanks for the information. I guess we should rename the package.

**Comment by wooorm** [comment]
@Rokt33r Ping! How’s it going with this? Can I do anything to help?

**Comment by Rokt33r** [comment]
@wooorm Sorry I was busy... I'm going to start working again in this week.

**Comment by wooorm** [comment]
Alright, no rush, just wanted to check in about whether there was something blocking this!

**Comment by Rokt33r** [comment]
Sorry for my long inactivity.... I'll start working from this weekend!

**Comment by Rokt33r** [comment]
Hast type defs have already registered to DefinitelyTyped. But the name was a bit weird, `hast-format`. So I submit a pr for renaming it. DefinitelyTyped/DefinitelyTyped#41542

**Comment by wooorm** [comment]
Updated the initial comment to reflect some of the packages that now have types!

**Comment by wooorm** [comment]
Going to close this because it’s mostly done, and more PRs can be sent to the individual repos!

Awesome job, folks, thanks!
