### ISSUE TITLE
Trailing whitespace in element is lost

### ISSUE THREAD

**Issue by thisconnect** [rehypejs/rehype#37]
### Subject of the issue

Trailing whitespace in element is lost if followed by text node. 

```html
a <strong>b </strong>c
```

### Your environment

*   **OS**: macOS
*   **Packages**: rehype
*   **Env**: Node 12.16.3

### Steps to reproduce

I tried to create a test, but I am not confident that it is 100% correct, please double check 
https://github.com/rehypejs/rehype/pull/36

### Expected behavior

The white space should be inside the strong element

### Actual behavior

There is no white space

**Comment by wooorm** [comment]
Are you certain this is from rehype core? Could it be one of the plugins?

**Comment by thisconnect** [comment]
> Are you certain this is from rehype core? Could it be one of the plugins?

Yes it could be from the remark plugins.

Did you see my PR with the test?

I tried to test what I think would be expected, but might have errors sorry.

**Comment by thisconnect** [comment]
Could it be one of the plugins?

I checked and it is using more or less:
1) rehype-parse
2) rehype-remark
3) remark-stringify

**Comment by thisconnect** [comment]
I could try to create another test somewhere, if you point me to where you think it would make sense.

**Comment by wooorm** [comment]
Could it be this bug? https://github.com/rehypejs/rehype-minify/issues/19

**Comment by wooorm** [comment]
I think it’s most probably that, which is now fixed: https://github.com/rehypejs/rehype-minify/commit/64c6206f2ac5c25a4465966a6e29ac696ed63f8b. Do let us know if your problem persists.

**Comment by thisconnect** [comment]
The `rehype-minify-whitespace` is in my dep tree as dependency of `hast-util-to-mdast` which wants a lower major version. I miserably failed at trying to manually replace it.

Seems to error see the PR https://github.com/syntax-tree/hast-util-to-mdast/pull/60
was there a breaking change?
