### ISSUE TITLE
keeping original entities

### ISSUE THREAD

**Issue by evilebottnawi** [rehypejs/rehype#41]
### Subject of the feature

Looks like it is impossible to keep original input of entities. I found it here https://github.com/rehypejs/rehype/tree/main/test/fixtures/entities.

### Problem

When I stringify my HTML I don't want to change entities content.

### Expected behavior

Keep them as they were written without changes.

### Alternatives

Provide option to keep them as is.

**Comment by wooorm** [comment]
Indeed, that’s a fact of ASTs: it’s abstract, unneeded stuff is lost. Similar to that we don‘t track if `"` or `'` are used around attribute values. We’re not a CST. To my knowledge, nobody has created a HTML -> CST parser. If a CST was used, it would also mean the syntax tree is rather unusable.

Btw: there are several cases in HTML where the document does not round trip. See the notes in [12.3 Serializing HTML fragments](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) (search for `roundtrip`)

Keeping character references as they were originally is not in the scope of this project. It’s also impossible a lot: plugins generate HTML a lot that wasn’t written by humans.

**Comment by evilebottnawi** [comment]
@wooorm What about if I want to write a plugin that only requires a certain style of writing entities? It is impossible? I agree it is not very important in many cases, but if I want to write a linter? Allow to get CST will be useful, I know that it may be outside of this project, but it was great feature due "To my knowledge, nobody has created a HTML -> CST parser.". Not high priority.

**Comment by wooorm** [comment]
CST: I’m now working on a markdown CST parser, and it takes a really long while to build something like that 😢 Although HTML is easier. It would need significant investment from companies probably too to sustain several months of work

linter: I think formatters are more interesting that linters, so maybe you can skip linting and instead focus on that? The parser we use to produce our AST is [parse5](https://github.com/inikulin/parse5/blob/HEAD/packages/parse5/docs/tree-adapter/default/interface-list.md), which does not provide info on character references. You might be able to use positional info to try and infer them though.

**Comment by evilebottnawi** [comment]
> linter: I think formatters are more interesting that linters, so maybe you can skip linting and instead focus on that?

**Comment by wooorm** [comment]
> Yes, but it is not it has not many and good API, rehype has it.

Thank you! What I wanted to say more is that it’s not possible to get access for us, because p5 doesn’t provide it.

> I know, but why do not hold it open, it is no high priority.

This is of so low priority to me, that is probably isn’t ever going to be supported. Hence, closing as wontfix makes more sense.

**Comment by evilebottnawi** [comment]
@wooorm Okay :disappointed:
