### ISSUE TITLE
Single quotes in style attributes are turned into html entities - css lint error

### ISSUE THREAD

**Issue by personaaleatoria** [rehypejs/rehype#47]
### Subject of the issue

Stringify is turning my single quotes into `&#x27;` and makes my css linter complain. 

### Your environment

*   **OS**: Ubuntu 20.04
*   **Packages**:

❯ yarn list --pattern "unified|rehype-parse|to-vfile|rehype-stringify|fs-extra"
yarn list v1.22.5
├─ @types/fs-extra@9.0.5
├─ fs-extra@9.0.1
├─ json-extra@0.5.0
│  └─ fs-extra@1.0.0
├─ postcss-markdown@0.36.0
│  └─ unified@7.1.0
├─ rehype-parse@7.0.1
├─ rehype-stringify@8.0.0
├─ rename-css-selectors@4.0.0-rc.2
│  └─ fs-extra@8.1.0
├─ retext@7.0.1
│  └─ unified@8.4.2
├─ to-vfile@6.1.0
└─ unified@9.2.0
Done in 0.49s.

*   **Env**: node 14.5.0, yarn 1.22.5

### Steps to reproduce

full minimal reproduction:

index.html

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="font-family: 'Some-font', sans-serif;">
</body>
</html>
```

index.js

```
const unified = require("unified");
const parser = require("rehype-parse");
const toVfile = require("to-vfile");
const stringify = require("rehype-stringify");
const fs = require("fs-extra");

const fileIn = "./index.html";
const fileOut = "./index-parsed.html";

unified()
  .use(parser)
  .use(stringify)
  .process(toVfile.readSync(fileIn), (err, data) => {
    if (err) {
      throw new Error(err);
    }
    fs.writeFileSync(fileOut, String(data));
  });

```

run with `node index.js`

Result

index-parsed.html

```
<!doctype html><html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="font-family: &#x27;Some-font&#x27;, sans-serif;">

</h1></body></html>
```

css lint error "property value expected at [7, 29]"

### Expected behavior

The quotes should remain as is in the og file.

### Actual behavior

A css lint error happens.

**Comment by wooorm** [comment]
That’s a bug in your CSS linter.

You might also turn [`allowDangerousCharacters`](https://github.com/syntax-tree/hast-util-to-html#optionsallowdangerouscharacters) in rehype-stringify on to not escape the apostrophe.

**Comment by personaaleatoria** [comment]
Thanks for the quick reply. You are right It turns out it's the vscode html validator. I turned off the "HTML: Validate Styles" setting and the error is gone.

**Comment by wooorm** [comment]
👍

You may want to raise it with them, as it's a bug there.

Thanks for using unified!
