### ISSUE TITLE
Bad logo rendering on github dark theme

### ISSUE THREAD

**Issue by lyderichti59** [rehypejs/rehype#49]
### Subject of the issue

The logo of Rehype is not well displayed in the Readme of the repository when I use Github's dark-theme

### Your environment

Firefox, Github dark theme

### Steps to reproduce

Enable Github Dark Theme, and open the repository page.

### Expected behavior

The logo should be fully readable

### Actual behavior

![image](https://user-images.githubusercontent.com/34691216/106391225-93eac380-63ec-11eb-84ef-c312a2843052.png)

**Comment by wooorm** [comment]
fixed!
