### ISSUE TITLE
[BUG] unexpected parsing behaviour for the same html tag

### ISSUE THREAD

**Issue by dreamer2q** [rehypejs/rehype#55]
### Subject of the issue

When parsing the html into syntax tree, the same html tag with different properties produces conflit syntax nodes.

### Your environment

*   **OS**: 
* win10 20h2
*   **Packages**: 
* rehype-parse
*   **Env**: 
* node 13, npm 6.12.0

### Steps to reproduce

```html
<card type="block" name="hr"></card>
<card type="block" name="localdoc"
    value="data:%7B%22status%22%3A%22done%22%2C%22source%22%3A%22transfer%22%2C%22src%22%3A%22https%3A%2F%2Fwww.yuque.com%2Fattachments%2Fyuque%2F0%2F2021%2Fpdf%2F2596791%2F1615361339259-26318a71-30c9-4f4f-ad67-d384b0b5c8af.pdf%22%2C%22name%22%3A%22Vue.js%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91%E5%9F%BA%E7%A1%80%E4%B8%8E%E9%A1%B9%E7%9B%AE%E5%AE%9E%E6%88%98%20-%20%E9%83%91%E9%9F%A9%E4%BA%AC(2020).pdf%22%2C%22ext%22%3A%22pdf%22%2C%22size%22%3A8758881%2C%22collapsed%22%3Atrue%2C%22margin%22%3Atrue%2C%22id%22%3A%22Uuryf%22%7D">
</card>
```

just parse the html content above and see its syntax tree, find out its difference.

### Expected behavior

The output should be same with different properties (since they only differ from its properties)

What should happen?

But they produce different syntax trees.

### Actual behavior

What happens instead?

see screenshot and find out its difference

![image](https://user-images.githubusercontent.com/56211747/115546468-a7187b80-a2d7-11eb-9bf5-953f4d8d5947.png)

![image](https://user-images.githubusercontent.com/56211747/115546494-b0094d00-a2d7-11eb-83e9-e1bcf439f7a7.png)

**Comment by wooorm** [comment]
It’s not really HTML though, is it? That looks like XML. They’re not custom elements either: those need a `-` in names.

What is the reason for passing such XML through rehype?

**Comment by dreamer2q** [comment]
However these <card> tags are embed inside html5 pagea.

should i need to use xml parser？

**Comment by wooorm** [comment]
> However these tags are embed inside html5 page.

Why are they there though? If you pass the HTML through https://validator.w3.org, you probably get an error.

> should i need to use xml parser？

If you have XML, use an XML parser; If you have HTML, you should probably fix the `card` “element”.

**Comment by dreamer2q** [comment]
Sorry for the late response

Indeed, I am using unified to convert `lake` format from `yuque.com` into `html` format.

The `lake` format is actually `html` tags with `customed tags` embbed, especially the `card` tag. the customed tags has `value` property which is `json string`  urlencoded, and the json string tells important properties (styles, informations, etc.).

So this is why I use `rehype` and I can not fix card since I cannot determine it.

See [this](https://www.yuque.com/xiaofan-ivhma/psgpnf/ll8593) for lake format page
See [this](https://www.yuque.com/xiaofan-ivhma/psgpnf/ll8593/lake) for raw lake format

**Comment by wooorm** [comment]
Is there documentation somewhere on the “lake format”?

You might solve this by using [webparser](https://github.com/Prettyhtml/prettyhtml/tree/master/packages/rehype-webparser)? 🤔

**Comment by dreamer2q** [comment]
> Is there documentation somewhere on the “lake format”?
> 
> You might solve this by using [webparser](https://github.com/Prettyhtml/prettyhtml/tree/master/packages/rehype-webparser)? 🤔

Great, `webparser` is exactly what I am looking for.

Thank U so much.

I think this can be closed.
