### ISSUE TITLE
SVG attributes getting transformed to invalid camel case

### ISSUE THREAD

**Issue by hendotcat** [rehypejs/rehype#56]
I'm trying to use rehype to process HTML containing inline SVGs, and the SVGs are coming out broken. Attributes like `stroke-linecap="round"` in the input are coming out invalid as `strokeLineCap="round"` in the output.

### Steps to reproduce

I've set up a [test repo](https://github.com/hendotcat/rehype-svg-bug) demonstrating the issue. Here's the code I'm running there. I hooked up the code to run in a GitHub Actions workflow too so you can [see it happen for yourself there](https://github.com/hendotcat/rehype-svg-bug/runs/2428624785?check_suite_focus=true) together with all the gory details about the environment. It seems to be environment-independent anyway as I first encountered this on my MacBook.

```javascript
const rehype = require("rehype")
const processor = rehype()

const html = `
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 8 8">
      <path stroke="#fff1e8" d="M0 6V3h1l1 1v2"/>
    </svg>
  </body>
</html>

console.log(processor.processSync(html).toString())
```

### Expected behavior

The SVG should come back out the other side `processor.processSync(html).toString()` and still be valid.

### Actual behavior

```
<!doctype html><html lang="en" dir="ltr"><head>
    <meta charset="utf-8">
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" strokeLineCap="round" strokeLineJoin="round" viewBox="0 0 8 8">
      <path stroke="#fff1e8" d="M0 6V3h1l1 1v2"></path>
    </svg>


</body></html>
```

I'm not 100% convinced this is a bug yet, so I'm half-anticipating hearing that I've misunderstood something here. Still thought it was worth reporting though just in case!

**Comment by hendotcat** [comment]
BTW I just tried running my test repo one more time except with `v10.0.0` instead of `v11.0.0` and the bug disappears! I'm actually satisfied with this as a temporary workaround for my own purposes. Hopefully it's helpful info for you as well as it narrows down the possible causes quite a lot!! 😅

**Comment by wooorm** [comment]
You’re right, it should work.
[I made a mistake refactoring](https://github.com/syntax-tree/hast-util-to-html/blame/001e9373dd96b7cdabb0b4159f43801804a706c8/lib/element.js#L40).

Fixed!

**Comment by hendotcat** [comment]
Oh cool! Had a feeling it'd be something a little deeper in the dependency tree of @unifiedjs packages. Really appreciate the link for the cause & fix: I'm keen to learn my way around these projects and this has helped a lot! Thank you very much!

**Comment by wooorm** [comment]
> I'm keen to learn my way around these projects and this has helped a lot!

Cool cool! Let us know if you find more bugs or have questions! ✨

**Comment by sergeysova** [comment]
I have the same issue but in the parser. `clip-rule` parsed as `clipRule`.
I wrote a custom compiler for svg, this brokes correct svg rendering.
