### ISSUE TITLE
Incorrectly parsed dash-cased svg properties as camelCase

### ISSUE THREAD

**Issue by sergeysova** [rehypejs/rehype#87]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-parse

### Link to runnable example

https://codesandbox.io/s/rehype-debug-forked-llth4

### Steps to reproduce

Parse svg with `clip-rule` via `rehype-parse`

```svg
<svg class='sc-gGLxEB set-color' fill='#8A8F98' height='16' stroke='none' viewBox='0 0 24 24' width='16'>
  <path clip-rule='evenodd'
        d='M6 0C2.68629 0 0 2.68629 0 6V18C0 21.3137 2.68629 24 6 24H18C21.3137 24 24 21.3137 24 18V6C24 2.68629 21.3137 0 18 0H6ZM7.54545 7H10.4545C10.7558 7 11 7.24421 11 7.54545V10.4545C11 10.7558 10.7558 11 10.4545 11H7.54545C7.24421 11 7 10.7558 7 10.4545V7.54545C7 7.24421 7.24421 7 7.54545 7ZM13.5455 7H16.4545C16.7558 7 17 7.24421 17 7.54545V10.4545C17 10.7558 16.7558 11 16.4545 11H13.5455C13.2442 11 13 10.7558 13 10.4545V7.54545C13 7.24421 13.2442 7 13.5455 7ZM10.4545 13H7.54545C7.24421 13 7 13.2442 7 13.5455V16.4545C7 16.7558 7.24421 17 7.54545 17H10.4545C10.7558 17 11 16.7558 11 16.4545V13.5455C11 13.2442 10.7558 13 10.4545 13ZM13.5455 13H16.4545C16.7558 13 17 13.2442 17 13.5455V16.4545C17 16.7558 16.7558 17 16.4545 17H13.5455C13.2442 17 13 16.7558 13 16.4545V13.5455C13 13.2442 13.2442 13 13.5455 13Z'
        fill-rule='evenodd'
        stroke='none'></path>
</svg>
```

### Expected behavior

`clip-rule` should stay in `properties` as is

### Actual behavior

Now `clip-rule` property stay in AST as `clipRule`.

### Runtime

Node v16

### Package manager

yarn v1

### OS

macOS

**Comment by wooorm** [comment]
Did you read about hast, the syntax tree used in rehype? Because, uhm, this is intentional.

**Comment by wooorm** [comment]
Also, when you have svg in html, then use this project.
When you have just svg, use xast.

**Comment by sergeysova** [comment]
Maybe, add option to disable this behavior?

**Comment by wooorm** [comment]
No.

Please read about this project and what it does. And read about the different syntax trees.

**Comment by sergeysova** [comment]
Thank you.
I didn't find parser for unified for xast. Do you know some?

**Comment by ChristianMurphy** [comment]
https://github.com/syntax-tree/xast-util-from-xml
